Lambda-School-Labs/Studium-BE

- auth/auth-router.js
- auth/authenticate-middleware.js
- index.js
- package-lock.json
- users/users-model.js
Made this branch when I noticed that the back end wasn't deploying properly
Removed bcryptjs from imports, deleted function from model, and updated server port default
> Dependancy update

- database/migrations/20200212184548_UsersTable.js
- database/migrations/20200212192438_decksTable.js
- database/migrations/20200212200122_SharedUsers.js
- database/migrations/20200212201212_Cards.js
- database/migrations/20200212204010_QuizResults.js
- knexfile.js
Initializing the database/schemas
Updated knexfile
> First commit

- apidoc/api_data.js
- apidoc/api_data.json
- apidoc/api_project.js
- apidoc/api_project.json
- routes/users/users-model.js
- routes/users/users-router.js
- routes/utils/findUIDMiddleware.js
> Finished get current user route

- apidoc/api_data.js
- apidoc/api_data.json
- apidoc/api_project.js
- apidoc/api_project.json
- routes/users/users-router.js
> Finished documentation for getAll route

- .github/workflows/nodejs.yml
- api/server.js
- data/dbConfig.js
- knexfile.js
- package.json
- routes/auth/registerRouter.spec.js
> Register endponits tested

- .eslintrc.json
- .github/workflows/nodejs.yml
- api/server.js
- knexfile.js
- package-lock.json
- package.json
- routes/auth/registerRouter.js
- routes/auth/registerRouter.spec.js
- routes/cards/cards-router.js
Fix for coverage paths in testing. 
Ran coverage locally and verified that test coverage didn't include the folder or files that we don't need coverage on.
> Fix coverage paths.

- .github/workflows/nodejs.yml
Fixed code climate failing to report the results. 
Ran code climate action after push.
> testing github actions db

- routes/utils/findDeckIDMiddleware.js
- routes/utils/findUIDMiddleware.js
> Middleware fix

- .gitignore
- package-lock.json
- package.json
Here is the initial commit for our BE, adding the following dependencies:
bcryptjs
cors
dotenv
express
helmet
jsonwebtoken
knex
pg
devDependencies:
jest
nodemon
supertest
> initial commit, added BE dependencies

- api/server.js
- index.js
I set-up the index.js, an api folder and a resources folder.
The api folder has the server.js file, which has been setup to import from the resources folder.
The resources folder holds folders for the following resources:
users, decks, cards, and sessions.
Each of these contains its router.js and model.js file (which are currently empty)
None of the above has been tested
> Server set-up

- db/db-config.js
Fixes environment
It has not been tested yet.
> Fixed environment

- db/migrations/20200527234641_create-decks-table.js
Creates decks table migrations.
This has yet to be tested.
> Created decks table migrations

- db/migrations/20200527234641_create-decks-table.js
- db/migrations/20200528232842_create-cards-table.js
Creates cards table migration file. 
Commented decks table migration file. 
This has not been tested as of yet.
> Created cards table migrations

- db/migrations/20200531212312_create-tags-table.js
- resources/cards/cards-model.js
- resources/cards/cards-router.js
Created tags table, as well as joined the tags and cards via endpoints.
No tests yet.
> Created tags table, joined cards & tags

- resources/decks/decks-model.js
- resources/decks/decks-router.js
Updated decks model & decks router to join tags to decks.
> Updated decks model & decks router

- README.md
Updated readme with the correct badges. 
Doesn't require testing.
> Readme updated with badges

- db/migrations/20200603232108_create-sessions-table.js
- package-lock.json
- resources/sessions/sessions-model.js
- resources/sessions/sessions-router.js
> created tables, router and model for session table

- api/server.js
- resources/decks/decks-model.js
- resources/decks/decks-router.js
Decks-router.js has all endpoints built. Awaiting testing.
This has yet to be tested!
> Fleshed out decks-router.js

- resources/decks/decks-router.js
Fixes endpoints in the decks router.
Has yet to be tested.
> Updated deck router

- resources/decks/decks-router.js
Adds in code to spit an error if conditions are not met. 
This has yet to be tested.
> Added in code to clarify an error if certain conditions are not met

- api/server.js
Modified server.js to allow sessions, tags, and cards routers to be used
> Modified server.js to allow sessions, tags, and cards routers to be used

- resources/tags/tags-router.js
Added module exports in tags router.
> Added module exports in tags router

- resources/cards/cards-model.js
- resources/tags/tags-model.js
Fixes issue where cards and tags models were calling from the decks table rather than their respective tables.
Note that the commit message does say decks. That's a typo. It should say cards instead.
This has yet to be tested.
> Updated models for cards and tags

- resources/cards/cards-router.js
- resources/decks/decks-router.js
- resources/tags/tags-router.js
Changes "X.length" to "X.length > 0" in routers.
> Updated how checking the ID in routers is performed

- resources/cards/cards-model.js
- resources/cards/cards-router.js
- resources/decks/decks-model.js
- resources/decks/decks-router.js
- resources/tags/tags-model.js
- resources/tags/tags-router.js
Removes for each methods and .first methods.
> Removes for each methods and .first

- resources/cards/cards-router.js
Fix cards router for specific card get request
This has yet to be tested.
> Fix cards router for specific card get request

- package.json
- resources/users/users-spec.js
> added tests to users

- auth/auth-router.js
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
>  took out the /api from auth router register and login

- auth/auth-router.js
fixed typo in file path to users-model in auth-router.js
> fixed typo in file path to users-model in auth-router.js

- auth/auth-router.js
changed to .add method from users-model in auth-router
> changed to .add method from users-model in auth-router

- auth/auth-router.js
> auth update

- auth/auth-router.js
> updated registration

- auth/auth-router.js
> newuser in auth

- auth/auth-router.js
> .first in auth

- resources/decks/decks-model.js
Hopefully joins cards to decks properly 
> Fix joining of cards to decks hopefully

- auth/auth-router.js
> .frist out

- resources/users/users-model.js
- resources/users/users-router.js
Adds a filter to get a specific user's decks based on User ID. 
> Added filter to get a users decks

- resources/users/users-model.js
- resources/users/users-router.js
Fixes 500 internal server error.
This has not been tested.
> Fixes internal error

- auth/authenticate-middleware.js
- resources/users/users-router.js
Added a specific /me endpoint that gets logged in users info
> Added a specific /me endpoint that gets logged in users info

- resources/users/users-router.js
> Import restricted middleware

- resources/users/users-router.js
Fixed users router
This has not been tested.
> Fixed users router

- resources/users/users-router.js
Fixed users router with right variable
> Fixed router with right variable

- resources/decks/decks-model.js
- resources/decks/decks-router.js
Add findCardsByDeckId to model and use it in Decks router
> Add findCardsByDeckId to model and use it in Decks router

- db/migrations/20200526221923_creeate-users-table.js
- db/migrations/20200527234641_create-decks-table.js
- db/migrations/20200528232842_create-cards-table.js
- db/migrations/20200531212312_create-tags-table.js
- db/migrations/20200603232108_create-sessions-table.js
- package-lock.json
- package.json
Fixes database with the following: 
- Turns all IDs to use UUID so that IDs are not easy to guess 
- Changes timestamps to integers so they can receive Date.now() functions
> Fixes all tables and restarts database

- db/migrations/20200527234641_create-decks-table.js
- db/migrations/20200528232842_create-cards-table.js
- db/migrations/20200603232108_create-sessions-table.js
> Fixes migrations again

- db/migrations/20200603232108_create-sessions-table.js
> Fixes sessions migration

- db/migrations/20200526221923_creeate-users-table.js
- db/migrations/20200527234641_create-decks-table.js
- db/migrations/20200528232842_create-cards-table.js
- db/migrations/20200531212312_create-tags-table.js
- db/migrations/20200603232108_create-sessions-table.js
> Fixes async and uuid

- db/migrations/20200526221923_creeate-users-table.js
- db/migrations/20200527234641_create-decks-table.js
- db/migrations/20200528232842_create-cards-table.js
- db/migrations/20200531212312_create-tags-table.js
- db/migrations/20200603232108_create-sessions-table.js
> Changes await into promises

- resources/sessions/sessions-model.js
Fix sessions model
Not tested.
> Fix sessions model

- db/migrations/20200603232108_create-sessions-table.js
> Fix integer values

- db/migrations/20200526221923_creeate-users-table.js
- db/migrations/20200527234641_create-decks-table.js
- db/migrations/20200528232842_create-cards-table.js
> Fixed integers into bigint

- resources/decks/decks-model.js
- resources/decks/decks-router.js
Fixes decks router and model to get sessions by deck id
Not tested
> Fixes decks router and model to get sessions by deck id
